CREATE TABLE IF NOT EXISTS roles (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '역할 식별 값',
	name VARCHAR(10) NOT NULL UNIQUE COMMENT '역할'
);

CREATE TABLE IF NOT EXISTS users (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 식별 값',
	username VARCHAR(10) NOT NULL UNIQUE COMMENT '사용자 아이디',
	password VARCHAR(255) NOT NULL COMMENT '사용자 비밀번호'
);

CREATE TABLE IF NOT EXISTS user_roles (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 역할 매핑 식별 값',
    user_id INT(11) UNSIGNED COMMENT '사용자 식별 값',
    role_id INT(11) UNSIGNED COMMENT '역할 식별 값',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);